# ---------------------------------------------------------------
# Theme Core Configuration Settings
# ---------------------------------------------------------------

# Allow to cache content generation.
cache:
  enable: false

# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------

# Meta tags in the website
site_meta:
  # If enable, `<meta name="format-detection" content="telephone=no">` will be inserted into the website.
  telephone_no: false
  # Set the background color of the Android Chrome navigation bar.
  # If enable, `<meta name="theme-color" content="#ffffff">` will be inserted into the website.
  theme_color: '#ffffff'

# Documentation: https://theme-stun.github.io/docs/zh-CN/guide/primary.html#favicon
favicon:
  small: /images/icons/favicon-16x16.png
  medium: /images/icons/favicon-32x32.png
  # ! --------------------------------------------------
  # ! If you don't know the following, please ignore it.
  # ! --------------------------------------------------
  # apple_touch_icon: /images/icons/apple-touch-icon.png
  # safari_pinned_tab:
  #   image: /images/icons/stun-logo.svg
  #   color: '#54bcff'
  # msapplication:
  #   image: /images/icons/favicon-144x144.png
  #   color: '#54bcff'
  #   config: /browserconfig.xml

# Assets
# In theme directory (source/css)
css: css
# In theme directory (source/js)
js: js
# In theme directory (source/images)
images: images
