# ---------------------------------------------------------------
# Theme Core Configuration Settings
# ---------------------------------------------------------------

# Allow to cache content generation.
cache:
  enable: false

# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------

# Meta tags in the website
site_meta:
  # If enable, `<meta name="format-detection" content="telephone=no">` will be inserted into the website.
  telephone_no: false
  # Set the background color of the Android Chrome navigation bar.
  # If enable, `<meta name="theme-color" content="#ffffff">` will be inserted into the website.
  theme_color: '#ffffff'
  # Set a canonical link tag for your Hexo site.
  # See: https://support.google.com/webmasters/answer/139066
  canonical: true
  # Inserts Open Graph data.
  # See: https://hexo.io/docs/helpers#open-graph
  open_graph: true
  # Speed up web pages by pre-resolving DNS.
  # See: https://www.keycdn.com/support/prefetching
  dns_prefetch:
    - https://cdn.jsdelivr.net

# Documentation: https://theme-stun.github.io/docs/zh-CN/guide/primary.html#favicon
favicon:
  small: /images/icons/favicon-16x16.png
  medium: /images/icons/favicon-32x32.png
  # ! --------------------------------------------------
  # ! If you don't know the following, please ignore it.
  # ! --------------------------------------------------
  # apple_touch_icon: /images/icons/apple-touch-icon.png
  # safari_pinned_tab:
  #   image: /images/icons/stun-logo.svg
  #   color: '#54bcff'
  # msapplication:
  #   image: /images/icons/favicon-144x144.png
  #   color: '#54bcff'
  #   config: /browserconfig.xml

# ---------------------------------------------------------------
# SEO Settings
# ---------------------------------------------------------------

# If true, will add site-subtitle to index page.
# Remember to set up your `subtitle` in Hexo `_config.yml`.
index_subtitle: false

webmaster_tools:
  # Google Webmaster tools verification.
  # See: https://www.google.com/webmasters/
  google:
  # Bing Webmaster tools verification.
  # See: https://www.bing.com/webmaster/
  bing:
  # Baidu Webmaster tools verification.
  # See: https://ziyuan.baidu.com/site/
  baidu:
  # 360 Webmaster tools verification.
  # see http://zhanzhang.so.com/
  qihu360:
  # Sougou Webmaster tools verification.
  # see http://zhanzhang.sogou.com/
  sougou:

# ---------------------------------------------------------------
# Other config
# ---------------------------------------------------------------

# Assets
# In theme directory (source/css)
css: css
# In theme directory (source/js)
js: js
# In theme directory (source/images)
images: images
