# ==================================================
# Basic config
# ==================================================

# Header menu navigation
menu:
  home: /
  archives: /archives
  categories: 
  tags: 
  about: 
  # XXX: /xxx

# Favicon
favicon: 

# Avatar in the sidebar
avatar: 

# Social links
social:
  github: 
  segmentfault: 
  twitter: 
  weibo: 
  wechat: 
  qq: 
  telegram: 

# Subscribe of email and rss
feed:
  mail: 
  # rss: 

# Stylesheets loaded in the <head>
stylesheets:
  - /css/index.css

# Scripts loaded in the end of the body
scripts:
  - /js/utils.js
  - /js/scroll.js
  - /js/header.js
  - /js/sidebar.js
  - /js/post.js

# CND for third libs
cdn:
  # css: 
  js:
    jquery: https://cdn.jsdelivr.net/npm/jquery@latest/dist/jquery.min.js
    velocity: https://cdn.jsdelivr.net/npm/velocity-animate@latest/velocity.min.js

# ==================================================
# Advanced config
# ==================================================

# Header navigation bar height
header_nav_height: 50px

# Header height
header_height: 80%

# Background image in the header
header_bg_img: 

# Background image in the footer
footer_bg_img: 

# Code highlight
# values:
# - light
# - dark
# - ocean
highlight_theme: light

# Header menu icon
# values: true or false
header_menu_icon_show: true

# Code wrap
# values: true or false
code_word_wrap: true

# Horizonal alignment of img
# values:
# - left
# - center
# - right
# 
# If you don't want to set the align of img
# please empty it, then img will show by default
img_horizonal_align: 

# Vertical alignment of text and images
# values:
# - top
# - middle
# - bottom
text_vertical_align_with_img: bottom

# Reward
reward:
  enable: false
  qr_img_url:
    alipay: 
    wechat: 

# Back to top
# values: true or false
back_to_top: true

# Copyright of articles
post_copyright:
  enable: true
  license: CC BY-NC-SA 4.0
  license_url: https://creativecommons.org/licenses/by-nc-sa/4.0/

# Copyright at the bottom of the site
site_copyright:
  enable: true
  start: 2019
  # If not set, default is the latest year
  end: 

# Custom text in the footer
footer_custom_text: 

# Blur filter effect of top image
top_img_blur:
  enable: false
  # Blutrriness
  level: 15px

# Avatar animation
# values:
# - shake
# - turn
avatar_animation: turn

# Tag cloud
# If not used, comment it or ignore it
tag:
  # Color for tag（please use quote to wrap value, only support HEX）
  start_color: '#a4d8fa'
  end_color: '#49b1f5'
  # Font size for tag
  min_font_size: 16
  max_font_size: 30
